version: "3.4" 

services:
    flaskapp:
        image: flaskapp
        build:
            context: .
            dockerfile: ./Dockerfile
            target: prod
        ports:
            -80:5000
        volumes:
            - .:/flask_starterkit:cached
        env_files: .env
